### ISSUE TITLE
Does this work automatically based on an interval or it's just manual 

### ISSUE THREAD

**Issue by aziz** [halo/LinkLiar#11]
Can this app automatically change the Mac addrress based on an interval or everything is manual?

**Comment by halo** [comment]
Hi! Would you mind giving the latest release a try? I need beta testers ;) My goal ist to change the MAC not per interval but whenever the interfaces change.

**Comment by aziz** [comment]
Great job man, I'll try it now. :+1:

**Comment by halo** [comment]
Make sure to use version `1.0.1` (or higher if available). Because I found a bug in 1.0.0 which caused the MAC address to be randomized *again* whenever the synchronization between the menu and the interfaces runs...

**Comment by aziz** [comment]
Just did! thanks :)

**Comment by halo** [comment]
So it seems that there is no way to detect if the end user just entered `sudo ifconfig en0 ether aa:bb:cc:dd:ee` in a Terminal manually (I subscribed to *every* System Configuration notification but none was triggered when I did that).

But I improved the interface change detection so that when **any** Interface comes up or down, the MAC addresses of **every** interface are synchronized with what you set in the status menu.

Your preferences are stored in the usual application preferences file. You can read those settings with `defaults read com.funkensturm.Link.plist` and even write them manually. The file is located in `~/Library/Preferences/com.funkensturm.Link.plist`.

Closing this issue for now.
