### ISSUE TITLE
Donation link?

### ISSUE THREAD

**Issue by ChrisCates** [halo/LinkLiar#31]
Donation link for BTC, ETH or Paypal?
Want to drop you $10 for the useful app.

**Comment by halo** [comment]
Thank you Chris. But I cannot accept payments due to tax and employment regulations.

I can assure you though that income generated through LinkLiar would not change my passion for the product. Rest assured that I will maintain it in the future as I have for the past 6 years :) Even though I'm rather busy at the moment and don't find the time for https://github.com/halo/LinkLiar/issues/27 as I would like to 😒

If you want to help, you can mention the software somewhere in a blog or leave a comment somewhere because I would like to make it available and known to as many people as possible. I have a feeling people looking for something like this don't find it as easily as they should :)

Again, thank you for your kind offer. Invest it wisely into something else ;)
