### ISSUE TITLE
For USB/Thunderbolt Ethernet, it will likely not prevent a leak?

### ISSUE THREAD

**Issue by WalkingCell** [halo/LinkLiar#36]
Hi, I'm just checking with you about this comment from back in 2017.
https://github.com/halo/LinkLiar/issues/21#issuecomment-308448668
Do this still being the case for USB/Thunderbolt Ethernet?
Do you have any tips in how to minimize this leak?

**Comment by halo** [comment]
Hi! Thank you for your question.

Yes, the leak still happens. WiFi has the same problem, but only once (as the spoofing persists even when you turn off WiFi, unlike plugging out an ethernet adapter).

Spontaneously, I know of no way to prevent macOS from talking over any interface as soon as it is activated, so that you'd have time to change the MAC address.

For Ethernet adapters, I suppose you could plug in the adapter but without the LAN cable. If you succeed to change the MAC address in that situation, you're good to go and can plug in the cable into the adapter.

As for the first-time-WiFi-spoof, put your Mac in a Faraday cage, turn on WiFi, wait for the spoofing to take effect, then remove the cage :)

I'd also like to mention that this is a general problem and not related to LinkLiar, so I'd encourage you to ask your question on [apple.stackexchange.com](https://apple.stackexchange.com/) or maybe  [security.stackexchange.com](https://security.stackexchange.com/). If you're precise in your wording you may get help (there are many questions about MAC addresses, but as far as I can tell non this specific).

I'll close this issue for now. Feel free to post more comments and maybe let me know how it went :)
