### ISSUE TITLE
LinkLiar always says I'm slipping 

### ISSUE THREAD

**Issue by JamieJ1** [halo/LinkLiar#41]
LinkLiar always shows me the slipping icon in the menu bar. Can anyone help? Using LinkLiar 2.1.1 on OSX 10.14.6

**Comment by halo** [comment]
That means the MAC address of one or more interfaces cannot be changed by `ifconfig`.

Do you have an external hub attached to your computer? Something that has an ethernet port? Those usually can't be changed. I actually have the same problem and thought about implementing a function to ignore that icon warning for particular interfaces.

**Comment by ajkblue** [comment]
I usually see this message whenever I’m using my usb-c to Ethernet adapter on my Mac. @halo I also think that adding an option to ignore certain interfaces if they’re leaking would be useful!

**Comment by JamieJ1** [comment]
Hi. Yes I have an external USB type A hub connected to my Mac but I had the same setup with my previous Mac and LL was working fine on that. So does they mean the MAC address of my actual computer is still being spoofed? If so, that’s all I really care about (unless the MAC address of my hub can be used to trace me?). Just a bit disconcerting as the Slipping icon is always visible.

**Comment by halo** [comment]
@JamieJ1 

> So does they mean the MAC address of my actual computer is still being spoofed?

Let me phrase it this way. If you set the default in LinkLiar to "random", every interface that *can* be spoofed *is being* spoofed. If any one interface cannot be spoofed (or is not configured to be spoofed), then the slippery icon will show.

> unless the MAC address of my hub can be used to trace me?

If you do not plug a cable into the hub, it cannot be used to trace you. The MAC address on cable interfaces is only known when you use a cable. The MAC address of WiFi interfaces is known as soon as you turn the WiFi on, because it will send out its MAC address eventually, to communicate with a hotspot.

> but I had the same setup with my previous Mac and LL was working fine on that

Either you had another hub (one that could be spoofed, whereas the new one maybe cannot be spoofed), or you did not configure LinkLiar to spoof the new hub.

@ajkblue 

> adding an option to ignore certain interfaces if they’re leaking would be useful!

To me it would make sense to not show the slippery icon for interfaces that are set to "ignore". Would that suffice? I think so.

**Comment by ajkblue** [comment]
@halo yes, that was what I was thinking would make the most sense in this case. Maybe also a little explanatory pop-up when clicking ignore could be useful, but I believe it’s pretty self-explanatory.

As a side note, do any of you know of a usb to Ethernet adapter that does allow spoofing?

**Comment by JamieJ1** [comment]
@halo 
> If you do not plug a cable into the hub, it cannot be used to trace you.

Bit confused. What good would a USB hub be if there were no cables connecting it to the computer and to devices?

> To me it would make sense to not show the slippery icon for interfaces that are set to "ignore". Would that suffice? I think so.

It would be useful if possible to have a sub-list of all attached devices and be able to see each of them with the status by them so you can see exactly what is protected throughout your system. Then I wouldn't mind if the main slipping icon was always in the Home bar, because at least I could go and see which device was causing the slip and try and fix it.

**Comment by halo** [comment]
> What good would a USB hub be if there were no cables connecting it to the computer and to devices

To be clear: as long as you do not plug a **network cable** (that is, a CAT cable) into the hub, there will be no leaking. MAC addresses are only used in network communication (at the very least from one end of the cable to the other), but not for USB devices, such as a keyboard or a printer.

> It would be useful if possible to have a sub-list of all attached devices

I think this might be a misunderstanding due to me not being clear. USB devices to not leak anything, so there is no use in showing those devices. LinkLiar is only concerned with Ethernet interfaces (Wi-Fi or Cable Ethernet).

**Comment by halo** [comment]
> As a side note, do any of you know of a usb to Ethernet adapter that does allow spoofing?

I have not found one yet. But fortunately the anonymity is pretty good if you bought one paying cash :)

Closing this issue because I don't think it's actionable.
