### ISSUE TITLE
“LinkLiar.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by kkovaletp** [halo/LinkLiar#58]
I've just installed the app onto my Monterey 12.6.1 (21G217) and once I started it, I got next error:

“LinkLiar.app” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

Please publish a signed version of the app, so that macOS accepts it without any issues

**Comment by halo** [comment]
Hi Konstantin! Thank you for posting the issue.

LinkLiar spoofs your MAC address, that is not something that a signed app is allowed to do (to my knowledge). Even [this similar app](https://apps.apple.com/app/wifispoof/id1192126677) on the App Store needs an [additional tool](https://support.sweetpproductions.com/topic/711/helper-tool-for-app-store-version-and-uninstaller) that you need to install manually in order for the spoofing to work.

Apart from that, I don't have an Apple Developer account (ca. 100 USD per year) so that's an additional hurdle.

If you install LinkLiar via `homebrew`, I suppose there is no warning. If you download the executable from Github, then you're forced to hold the option-key while installing as per [these instructions](https://halo.github.io/LinkLiar/installation.html).

Sorry I don't have better news, but I don't think there is a way around. I'll close this for now, feel free to open it again in case new info surfaces.
